diegoberaldin/RaccoonForLemmy

- core-api/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/api/dto/CreateCommentReportForm.kt
- core-api/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/api/dto/CreatePostReportForm.kt
This PR fixes a typo in the authorization param of the create report request body for posts and comments.
> fix: create report request body

- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/postdetail/PostDetailViewModel.kt
This PR avoid inserting the same comment over and over again when downloading children of a parent comment (which could never be found if the comment itself was deleted).
> fix: avoid comment duplication

- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/components/CommunityHeader.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/components/CommunityItem.kt
- remove` &amp;` from community titles
- show community title in header when displaying detail screen
> fix: community name and titles

- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/postdetail/PostDetailScreen.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/postdetail/PostDetailViewModel.kt
- domain-lemmy/data/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/data/CommentModel.kt
There is a problem with comment loading if a comment has deleted children, because the button to fetch more comments remains always visible. This PR fixes that issue and moves the logic to display the button in the ViewModel.
> fix: load more button visibility

- core-md/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/compose/CustomMarkdown.kt
- core-md/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/compose/DefaultMarkwonProvider.kt
- core-md/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/di/MarkwonModule.kt
- core-md/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/plugins/ClickableImagesPlugin.kt
- core-md/src/iosMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/compose/CustomMarkdown.kt
#77 removed temporarily clickable images due to glitches while rendering. This PR aims at reintroducing the feature with a new plugin.
> fix: reintroduce clickable images in markdown

- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/components/PostCardTitle.kt
- core-md/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/di/MarkwonModule.kt
- core-md/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/provider/DefaultMarkwonProvider.kt
- core-md/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/provider/MarkwonProvider.kt
MarkwonProvider should exist as a `single` binding. This works provided that the callbacks for opening URLs and images are consistent.
> refactor: better md management

- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/postdetail/PostDetailScreen.kt
Cross posts should point to the detail of the post in the other community instead of the community detail.
> fix: cross post destination

- core-commonui/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/CustomTextToolbar.kt
- core-commonui/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/di/Utils.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/di/Utils.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/modals/RawContentDialog.kt
- core-commonui/src/iosMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/di/Utils.kt
This PR adds a custom "Search" action to the raw content dialog to open a browser and search for the selected text.
<div align="center">
</div>
> feat: add custom menu to search in raw content

- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/communitydetail/CommunityDetailScreen.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/communitydetail/CommunityDetailViewModel.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/modals/ListingTypeBottomSheet.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/modals/SortBottomSheet.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/userdetail/UserDetailScreen.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/userdetail/UserDetailViewModel.kt
- core-utils/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/utils/RememberCallback.kt
- feature-home/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/home/postlist/PostListScreen.kt
- feature-home/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/home/postlist/PostListViewModel.kt
- feature-profile/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/profile/logged/ProfileLoggedScreen.kt
- feature-profile/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/profile/logged/ProfileLoggedViewModel.kt
- feature-search/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/search/main/ExploreScreen.kt
- feature-search/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/search/main/ExploreViewModel.kt
When the result set changed (e.g. after changing sort type or search criterion) when opening a detail from a list led to the wrong item. This PR solves the issue by providing item unique IDs.
> fix: open detail from list

- domain-identity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/identity/usecase/DefaultLoginUseCase.kt
As per title, instead of starting with fresh new settings for new accounts, the ones of the anonymous account are copied.
> enhancement: copy anon settings on new accounts

- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/instanceinfo/InstanceInfoMviModel.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/instanceinfo/InstanceInfoScreen.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/instanceinfo/InstanceInfoViewModel.kt
- domain-lemmy/data/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/data/ListingType.kt
- domain-lemmy/data/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/data/SortType.kt
- feature-home/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/home/postlist/PostsTopBar.kt
- feature-search/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/search/main/ExploreTopBar.kt
- feature-search/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/search/multicommunity/detail/MultiCommunityScreen.kt
This PR adds the possibility to sort communities in the instance detail screen, with some of the ordering that seem to work:
- Active
- Hot
- New
- New comments
- Most comments
- Top (every interval).
> feat: sort communities instance detail

- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/communitydetail/CommunityDetailScreen.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/components/CommunityHeader.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/components/UserHeader.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/instanceinfo/InstanceInfoScreen.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/instanceinfo/InstanceInfoViewModel.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/saveditems/SavedItemsViewModel.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/userdetail/UserDetailScreen.kt
- feature-search/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/search/managesubscriptions/ManageSubscriptionsMviModel.kt
- feature-search/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/search/managesubscriptions/ManageSubscriptionsScreen.kt
- feature-search/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/search/managesubscriptions/ManageSubscriptionsViewModel.kt
This PR adds the "old" sort option for communities in instance detail, improves the loading of such elements and moves the ℹ️ buttons to a 🚦 button in the app bar in both community and user detail.
> fix: instance detail

- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/communitydetail/CommunityDetailScreen.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/createcomment/CreateCommentMviModel.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/createcomment/CreateCommentScreen.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/createcomment/CreateCommentViewModel.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/instanceinfo/InstanceInfoViewModel.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/postdetail/PostDetailScreen.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/userdetail/UserDetailScreen.kt
- core-notifications/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/notifications/DefaultNotificationCenter.kt
- core-notifications/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/notifications/NotificationCenter.kt
- domain-identity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/identity/usecase/DefaultLogoutUseCase.kt
- domain-lemmy/data/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/data/SearchResultType.kt
- domain-lemmy/repository/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/repository/CommunityRepository.kt
- feature-home/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/home/postlist/PostListScreen.kt
- feature-search/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/search/main/ExploreMviModel.kt
- feature-search/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/search/main/ExploreScreen.kt
- feature-search/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/search/main/ExploreViewModel.kt
- feature-search/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/search/multicommunity/detail/MultiCommunityScreen.kt
This PR fixes some more problems with reloading screens after navigation, fixes a crash in the explore screen and a bug that prevented sorting from applying to the post list in community detail.
> fix: remove unnecessary reloads

- README.md
- feature-inbox/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/inbox/mentions/InboxMentionsMviModel.kt
- feature-inbox/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/inbox/mentions/InboxMentionsScreen.kt
- feature-inbox/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/inbox/mentions/InboxMentionsViewModel.kt
- feature-inbox/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/inbox/messages/InboxMessagesMviModel.kt
- feature-inbox/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/inbox/messages/InboxMessagesScreen.kt
- feature-inbox/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/inbox/messages/InboxMessagesViewModel.kt
- feature-inbox/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/inbox/replies/InboxRepliesMviModel.kt
- feature-inbox/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/inbox/replies/InboxRepliesScreen.kt
- feature-inbox/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/inbox/replies/InboxRepliesViewModel.kt
In the inbox screens, after chaning the filters (read/unread) if you tried to open an item you could end up opening the item that occupied that position before the filter change.
This PR solves that problem and introduces automatic scroll to top when filters are changed like in the rest of the app sections, this behaviour was added later and the inbox screen had been left behind.
> fix: inbox opening detail and loading

- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/communitydetail/CommunityDetailScreen.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/postdetail/PostDetailScreen.kt
- core-commonui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/userdetail/UserDetailScreen.kt
- shared/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/App.kt
This PR reintroduces the sliding transitions between screens that were removed due to an issue with opening related posts (cross-posts).
If custom unique keys are provided by content, two adjacent PostDetailScreen can now sit in the navigation stack with transitions, so it was possible to reintroduce them.
> enhancement(app): reintroduce screen transitions

- core-api/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/api/dto/CommentAggregates.kt
- core-api/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/api/dto/CommunityAggregates.kt
- core-api/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/api/dto/PersonAggregates.kt
- core-api/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/api/dto/PostAggregates.kt
- core-api/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/api/dto/SiteAggregates.kt
- core-api/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/api/dto/SiteView.kt
- domain-lemmy/repository/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/repository/utils/Mappings.kt
- feature-home/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/home/postlist/PostListViewModel.kt
This PR solves some issues reported with Lemmy 0.19 instances.
The migration has already been done in #57 more than a month ago theoretically, but some fields have become optional  in the meantime (e.g. the `id` field in `PostAggregates`, `CommunityAggregates`, `CommentAggregates`, `SiteAggregates`) breaking the compatibility.
I'm waiting to see what other things the API developers broke (if any) before merging this 🤣🤣🤣
> fix(api): improve Lemmy 0.19 compatibility

- shared/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/ui/navigation/TabNavigationItem.kt
This PR prevents text in navigation bar items from spanning multiple lines.
> fix: navigation bar text

- androidApp/build.gradle.kts
- androidApp/src/main/java/com/github/diegoberaldin/raccoonforlemmy/android/MainApplication.kt
- core-md/build.gradle.kts
- core-md/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/provider/DefaultMarkwonProvider.kt
- core-utils/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/utils/StringUtils.kt
- gradle/libs.versions.toml
As per title, this PR adds the support for GIF files both in post cards and when embedded in markdown text, such as custom emojis.
This required changing the coil images plugin for Markwon because it didn't support adding the GIF decoder to the Image Loader.
> feat: add GIF support

- core/persistence/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/persistence/DefaultDriverFactory.kt
- gradle/libs.versions.toml
This PR migrates from the deprecated `android-database-sqlcipher` to the new `sqlcipher-android` library.
> chore: update sqlcipher

- core/commonui/lemmyui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/lemmyui/TextFormattingBar.kt
- core/utils/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/utils/compose/OnClick.kt
- unit/createcomment/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/createcomment/CreateCommentScreen.kt
This PR solves a bug that led to the content of text fields with a formatting bar to be overridden instead of appending the formatted part. The bug was due to the new onClick modifier introduced in #414.
> fix: formatting bar actions

- core/md/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/plugins/MarkwonSpoilerPlugin.kt
- core/md/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/provider/DefaultMarkwonProvider.kt
Thanks rb_c for this report, it was a really tricky behaviour!
> fix: do not collapse comments while clicking on spoilers

- core/navigation/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/navigation/DefaultDrawerCoordinator.kt
- core/navigation/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/navigation/DrawerCoordinator.kt
- shared/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/App.kt
- unit/drawer/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/drawer/ModalDrawerContent.kt
This PR prevents the drawer from being opened when changing instance from the top bar.
> fix: close drawer after instance change

- unit/zoomableimage/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/zoomableimage/ZoomableImageViewModel.kt
This is a temporary workaround for Whatsapp sharing broken.
> chore: share images as text

- core/commonui/detailopener-impl/build.gradle.kts
- core/commonui/detailopener-impl/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/detailopener/impl/DefaultDetailOpener.kt
- shared/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/di/SharedModule.kt
- unit/about/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/about/AboutDialog.kt
- unit/about/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/about/AboutDialogMviModel.kt
- unit/about/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/about/AboutDialogViewModel.kt
- unit/about/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/about/di/AboutModule.kt
This PR reduces the need for "guest mode" when resolving community references, generalizing the algorithm for the "search on local instance before, on foreign instance later" that was used in the About dialog to open the project's community.
> refactor: improve community opening on other instances

- domain/identity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/identity/repository/DefaultIdentityRepository.kt
- domain/identity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/identity/repository/IdentityRepository.kt
Sometimes at app startup the state is not in synch with the validity of the token.
> refactor: convert isLogged to state

- unit/messages/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/messages/InboxMessagesMviModel.kt
- unit/messages/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/messages/InboxMessagesScreen.kt
- unit/messages/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/messages/InboxMessagesViewModel.kt
- unit/messages/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/messages/components/ChatCard.kt
- unit/messages/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/messages/components/ChatCardPlaceholder.kt
This PR removes the unread indicator for chats and the ability to mark private messages as read because it does not seem to work.
> chore: remove unread indicator for private messages

- core/commonui/lemmyui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/lemmyui/PostCardBody.kt
- core/commonui/lemmyui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/lemmyui/PostCardTitle.kt
- core/markdown/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/Utils.kt
This PR fixes a couple of other issues with MD, mainly the blank lines being ripped off and some missing styles (where the default font family popped up instead of the custom one).
> fix: markdown render improvements

- core/markdown/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/CustomMarkdownImage.kt
- core/markdown/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/CustomMarkdownSpoiler.kt
- core/markdown/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/CustomMarkdownWrapper.kt
- core/markdown/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/Regexes.kt
- core/markdown/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/Utils.kt
This PR treats "paragraph" blocks containing only images (non-inline images) like regular images.
> fix:  md non inline images

- core/commonui/lemmyui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/lemmyui/FabNestedScrollConnection.kt
- core/navigation/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/navigation/DefaultNavigationCoordinator.kt
- shared/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/MainScreen.kt
This PR removes the debounce intervals that were once needed for navigation to avoid transition crashes but are no longer necessary and  degraded the user experience (as observed by some people).
> refactor: remove navigation debounce

- core/markdown/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/CustomMarkdownWrapper.kt
Post body max lines was not working any more after #536 (there was even a crash fixed in #547 along the way). This PR applies a max height constraint to markdown containers if the maxLines parameter is passed. It is not possible, as in the previous implementation, to account for exact lines because I have no control on the underlying renderer, but for the moment this should do.
> fix post body max height

- unit/communitydetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt
- unit/userdetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/userdetail/UserDetailScreen.kt
This PR adds the "share" option in community and user detail screens. As usual, if you are on a different instance, you can choose among multiple URL formats, one pointing to your local instance and the other to the original instance.
> feat: add share option to community and user detail

- domain/identity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/identity/repository/DefaultIdentityRepository.kt
- domain/identity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/identity/repository/IdentityRepository.kt
- unit/postlist/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/postlist/PostListScreen.kt
- unit/postlist/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/postlist/PostListViewModel.kt
This PR improves logged in state detection at startup, especially in case a network error occurs and the post list is refreshed.
> fix: better detection of logged state at startup

- unit/communitydetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt
- unit/communityinfo/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/communityinfo/CommunityInfoScreen.kt
This PR removes a blank space under the community header and adds the Lemmy handle in the community info screen.
> enhancement: add community handle in info screen and remove spacing

- CONTRIBUTING.md
- core/navigation/build.gradle.kts
- core/navigation/src/androidUnitTest/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/navigation/DefaultDrawerCoordinatorTest.kt
- core/navigation/src/androidUnitTest/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/navigation/DefaultNavigationCoordinatorTest.kt
- core/testutils/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/testutils/DispatcherTestRule.kt
- gradle/libs.versions.toml
This PR adds some test cases for `DefaultNavigationCoordinator`.
> chore: add test for DefaultNavigationCoordinator

- core/notifications/build.gradle.kts
- core/notifications/src/androidUnitTest/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/notifications/DefaultContentResetCoordinatorTest.kt
- core/notifications/src/androidUnitTest/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/notifications/DefaultNotificationCenterTest.kt
Adds tests for the `:core:notifications` module.
> chore: add tests for :core:notifications

- core/commonui/modals/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/modals/ListingTypeBottomSheet.kt
- core/commonui/modals/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/modals/SortBottomSheet.kt
- core/notifications/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/notifications/NotificationCenterEvent.kt
- feature/search/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/search/main/ExploreScreen.kt
- feature/search/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/search/main/ExploreViewModel.kt
- feature/settings/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsScreen.kt
- feature/settings/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsViewModel.kt
- feature/settings/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/settings/main/SettingsScreen.kt
- feature/settings/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/settings/main/SettingsViewModel.kt
- shared/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/MainScreen.kt
- unit/accountsettings/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/accountsettings/AccountSettingsScreen.kt
- unit/accountsettings/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/accountsettings/AccountSettingsViewModel.kt
- unit/communitydetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt
- unit/communitydetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/communitydetail/CommunityDetailViewModel.kt
- unit/instanceinfo/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/instanceinfo/InstanceInfoScreen.kt
- unit/instanceinfo/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/instanceinfo/InstanceInfoViewModel.kt
- unit/multicommunity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityScreen.kt
- unit/multicommunity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityViewModel.kt
- unit/postlist/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/postlist/PostListScreen.kt
- unit/postlist/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/postlist/PostListViewModel.kt
- unit/saveditems/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/saveditems/SavedItemsScreen.kt
- unit/saveditems/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/saveditems/SavedItemsViewModel.kt
- unit/userdetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/userdetail/UserDetailScreen.kt
- unit/userdetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/userdetail/UserDetailViewModel.kt
This PR fixes the sort and feed type settings which was accidentally broken by #587 when altering the lifecycle of screen models.
> fix: add event filters based on screen

- core/commonui/detailopener-api/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/detailopener/api/DetailOpener.kt
- core/commonui/detailopener-impl/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/detailopener/impl/DefaultDetailOpener.kt
- unit/communitydetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt
- unit/createpost/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/createpost/CreatePostScreen.kt
- unit/createpost/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/createpost/CreatePostViewModel.kt
- unit/drafts/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/drafts/DraftsScreen.kt
- unit/drafts/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/drafts/components/DraftCard.kt
- unit/postdetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/postdetail/PostDetailScreen.kt
- unit/postlist/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/postlist/PostListScreen.kt
- unit/selectcommunity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/selectcommunity/SelectCommunityDialog.kt
- unit/userdetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/userdetail/UserDetailScreen.kt
A user has complained recently about not being able to create posts, because it's difficult to understand that you have to be inside a community to create one (in that community).
This PR makes it possible for logged users to create posts even from the home screen, but they will have to manually select the community in a similar fashion to what happens for cross posts.
> feat: create post from home

- domain/identity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/identity/di/IdentityModule.kt
- domain/identity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/identity/repository/DefaultIdentityRepository.kt
- domain/lemmy/data/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/data/UserModel.kt
- unit/myaccount/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/myaccount/ProfileLoggedMviModel.kt
- unit/myaccount/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/myaccount/ProfileLoggedScreen.kt
- unit/myaccount/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/myaccount/ProfileLoggedViewModel.kt
- unit/myaccount/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/myaccount/di/MyAccountModule.kt
Centralize remembering profile and moderator status in `IdentityRepository` to have a single source of truth about the current user.
> enhancement: optimize current user mod status

- core/commonui/detailopener-impl/src/androidUnitTest/kotlin/DefaultDetailOpenerTest.kt
- core/commonui/detailopener-impl/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/detailopener/impl/DefaultDetailOpener.kt
- core/commonui/lemmyui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/lemmyui/Options.kt
- domain/lemmy/repository/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/repository/CommunityRepository.kt
- domain/lemmy/repository/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/repository/DefaultCommunityRepository.kt
- unit/communitydetail/build.gradle.kts
- unit/communitydetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt
- unit/communitydetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/communitydetail/CommunityDetailViewModel.kt
- unit/explore/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/explore/ExploreScreen.kt
- unit/explore/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/explore/ExploreViewModel.kt
- unit/explore/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/explore/components/ExploreTopBar.kt
- unit/explore/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/explore/di/ExploreModule.kt
- unit/postdetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/postdetail/PostDetailScreen.kt
- unit/userdetail/build.gradle.kts
- unit/userdetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/userdetail/UserDetailScreen.kt
This PR makes use of the "new" modularized explore screen introduced in #619 to open an "Explore instance" screen from a community or user detail.
This will make it possible to search local posts, community, users, etc. as guests on other instances.
> feat: explore other instance

- core/notifications/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/notifications/NotificationCenterEvent.kt
- unit/communitydetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/communitydetail/CommunityDetailViewModel.kt
- unit/explore/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/explore/ExploreViewModel.kt
- unit/managesubscriptions/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/managesubscriptions/ManageSubscriptionsViewModel.kt
This PR adds a notification to make sure the Explore screen and manage subscription screen are in sync if a subscription changes from the community detail.
> enhancement: notify subscription event

- core/commonui/lemmyui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/lemmyui/CommunityItem.kt
- unit/managesubscriptions/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/managesubscriptions/ManageSubscriptionsScreen.kt
- unit/multicommunity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityMviModel.kt
- unit/multicommunity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityScreen.kt
- unit/multicommunity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityViewModel.kt
- unit/multicommunity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/multicommunity/editor/MultiCommunityEditorScreen.kt
- unit/multicommunity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/multicommunity/editor/MultiCommunityEditorViewModel.kt
- unit/multicommunity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/multicommunity/utils/DefaultMultiCommunityPaginator.kt
This PR solves a series of issues related to multi-communities:
- post not being loaded in the correct order
- initial state not being dealt with correctly
- actions (like/dislike save) not being available
- editor screen layout
- in the manage subscription screen "unsubscribe" and "delete" options were inverted.
> fix: multi community behaviour

- core/markdown/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/CustomMarkdownWrapper.kt
- unit/filteredcontents/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/filteredcontents/FilteredContentsMviModel.kt
- unit/filteredcontents/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/filteredcontents/FilteredContentsScreen.kt
- unit/filteredcontents/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/filteredcontents/FilteredContentsViewModel.kt
- unit/myaccount/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/myaccount/ProfileLoggedScreen.kt
This PR fixes a but reported [here](https:///feddit.it/post/6718289) with comment link opening as well as a state restoration issue which led the moderated contents and votes screens (accessible from Profile) to crash when the app was not in the foreground.
> fix: comment link opening and state restoration

- core/commonui/components/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/components/ZoomableImage.kt
- domain/lemmy/data/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/data/PostModel.kt
There were a couple of problems in the zoomable image screen:
- instead of giving precedence to the thumbnail URL, the URL of the post was preferred (the correct order should be the other way round)
- the image was downscaled and zoom was limited to a small range.
This PR fixes both issues.
> fix: zoomable image

- core/commonui/components/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/components/FloatingActionButtonMenu.kt
- core/commonui/lemmyui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/lemmyui/PostCard.kt
- core/commonui/lemmyui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/lemmyui/PostCardFooter.kt
- unit/filteredcontents/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/filteredcontents/FilteredContentsMviModel.kt
- unit/filteredcontents/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/filteredcontents/FilteredContentsScreen.kt
- unit/filteredcontents/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/filteredcontents/FilteredContentsViewModel.kt
- unit/myaccount/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/myaccount/ProfileLoggedMviModel.kt
- unit/myaccount/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/myaccount/ProfileLoggedScreen.kt
- unit/myaccount/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/myaccount/ProfileLoggedViewModel.kt
- unit/postdetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/postdetail/PostDetailViewModel.kt
This PR contains some fixes for bugs (kinda) introduced by #681 and #684:
- changes the FAB icon to avoid users thinking it just allows to create new contents
- resets unread comments after opening a post detail
- fade read posts in Upvotes & downvotes screen
- shows unread comments in Profile and Upvotes & downvotes screens.
> chore: change fab icon and read/unread improvements

- feature/profile/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/profile/main/ProfileMainScreen.kt
This PR inverts the dialog buttons for logout confirmation (sorry!).
> fix: logout confirmation dialog buttons

- core/commonui/components/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/components/DraggableSideMenu.kt
- core/commonui/lemmyui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/lemmyui/CommunityHeader.kt
- core/commonui/lemmyui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/lemmyui/UserHeader.kt
- core/navigation/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/navigation/DefaultNavigationCoordinator.kt
- core/navigation/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/navigation/NavigationCoordinator.kt
- shared/build.gradle.kts
- shared/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/App.kt
- shared/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/MainScreen.kt
- unit/communitydetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt
- unit/communityinfo/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/communityinfo/CommunityInfoScreen.kt
- unit/userdetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/userdetail/UserDetailScreen.kt
- unit/userinfo/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/userinfo/UserInfoScreen.kt
Since #702 introduced a custom draggable menu which can be really handy, this PR moves the user and community info from bottom sheets to this side menu, which can be opened via an :information_source: button in the community or user header.
I like this idea better because the informational screen is referred to as "sidebar" among Lemmy's user base and people assume it will be displayed as a "side" widget, not as a full screen or a dialog.
> feat: community/user info in side menu

- core/notifications/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/notifications/NotificationCenterEvent.kt
- feature/profile/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/profile/main/ProfileMainScreen.kt
- unit/myaccount/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/myaccount/ProfileActionMenu.kt
- unit/myaccount/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/myaccount/ProfileLoggedScreen.kt
This PR reverts #677 and brings back a fixed UI with the action menu in the profile screen for logged users.
> enhancement: restore profile action menu

- core/appearance/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/appearance/theme/Fonts.kt
- core/commonui/modals/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/modals/AppIconBottomSheet.kt
- core/resources/build.gradle.kts
- core/resources/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/resources/di/Utils.kt
- core/resources/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/resources/CoreResources.kt
- core/resources/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/resources/DefaultCoreResources.kt
- core/resources/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/resources/Utils.kt
- core/resources/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/resources/di/CoreResourcesModule.kt
- core/resources/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/resources/di/Utils.kt
- core/resources/src/iosMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/resources/di/Utils.kt
- shared/build.gradle.kts
- shared/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/di/DiHelper.kt
- shared/src/iosMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/di/DiHelper.kt
- unit/about/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/about/AboutDialog.kt
- unit/choosefont/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/choosefont/FontFamilyBottomSheet.kt
This PR refactors `:core:resources` in order to have injectable resources via Koin, provided that any implementation complies with the CoreResources contract.
This will make a lot easier to migrate towards Compose Multiplatform >1.6.0 resource management without expect/actual mechanism to load raw resources differently on different platforms.
For drawables it could alread be done, however the transition is not possible for fonts, because it is currently [not supported(https://github.com/JetBrains/compose-multiplatform/issues/4229) to load custom fonts in a multi-module project.
Anyway this refactoring makes things more configurable and flexible so I am merging it to the main branch.
> refactor: injectable resources

- unit/myaccount/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/myaccount/ProfileLoggedScreen.kt
The access to moderator tools had accidentally been removed in #712. This PR fixes it.
> fix: moderator tools access from profile

- core/api/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/api/dto/Person.kt
- core/commonui/lemmyui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/lemmyui/CollapsedCommentCard.kt
- core/commonui/lemmyui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/lemmyui/CommentCard.kt
- core/commonui/lemmyui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/lemmyui/CommunityAndCreatorInfo.kt
- core/commonui/lemmyui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/lemmyui/IndicatorChip.kt
- core/commonui/lemmyui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/lemmyui/UserHeader.kt
- domain/lemmy/data/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/data/UserModel.kt
- domain/lemmy/repository/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/repository/DefaultSiteRepository.kt
- domain/lemmy/repository/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/repository/utils/Mappings.kt
- unit/explore/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/explore/ExploreScreen.kt
- unit/filteredcontents/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/filteredcontents/components/ModdedCommentCard.kt
- unit/postdetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/postdetail/PostDetailScreen.kt
- unit/saveditems/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/saveditems/SavedItemsScreen.kt
This PR adds an indicator for bot accounts in comments (post detail, explore, saved items, moderated and filtered contents) and in user detail.
> feat: show bot accounts in comments

- feature/settings/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/settings/main/SettingsViewModel.kt
The Home and Explore feeds should be reset after changing NSFW inclusion criteria.
> enhancement: add reset after changing NSFW setting

- core/markdown/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/CustomMarkdownWrapper.kt
This PR simplifies the `CustomMarkdownWrapper` Composable and solved the bug due to which the max body height calculated based on the number of lines was reserved as default space for any post body.
> fix: post body max height

- androidApp/src/main/AndroidManifest.xml
This PR makes it possible to receive contents from the system share menu even when using the alternate icon.
> fix: add intent for activity alias

- unit/mentions/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/mentions/InboxMentionsViewModel.kt
- unit/messages/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/messages/InboxMessagesViewModel.kt
- unit/replies/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/replies/InboxRepliesViewModel.kt
As per title, this PR makes sure the inbox is in a consistent state after account switch.
> fix: refresh completely inbox after account switch

- core/appearance/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/appearance/theme/DefaultBarColorProvider.kt
- core/commonui/components/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/components/BottomSheetHandle.kt
This PR fixes the status bar (especially in transparent mode) for light theme.
Since bottom sheets with long titles (like the "System notification and navigation bar theme" one) were ugly, the text alignment is fixed here too.
> fix: status bar color for light theme

- unit/communitydetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt
- unit/drafts/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/drafts/DraftsScreen.kt
- unit/explore/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/explore/ExploreScreen.kt
- unit/filteredcontents/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/filteredcontents/FilteredContentsScreen.kt
- unit/licences/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/licences/LicencesScreen.kt
- unit/manageban/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/manageban/ManageBanScreen.kt
- unit/modlog/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/modlog/ModlogScreen.kt
- unit/multicommunity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/multicommunity/detail/MultiCommunityScreen.kt
- unit/myaccount/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/myaccount/ProfileLoggedScreen.kt
- unit/postdetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/postdetail/PostDetailScreen.kt
- unit/postlist/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/postlist/PostListScreen.kt
- unit/rawcontent/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/rawcontent/RawContentDialog.kt
- unit/reportlist/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/reportlist/ReportListMviModel.kt
- unit/reportlist/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/reportlist/ReportListScreen.kt
- unit/reportlist/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/reportlist/ReportListViewModel.kt
- unit/saveditems/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/saveditems/SavedItemsScreen.kt
- unit/userdetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/userdetail/UserDetailScreen.kt
This PR fixes a visual bug due to report list not extending to full width, which resulted in an ugly collapsed loader when the list was empty during refresh.
Additionally, a back to top effect was added when changing the report type (unresolved vs all).
> fix: report list loading indicator

- .github/workflows/android.yml
- core/commonui/detailopener-impl/src/androidUnitTest/kotlin/DefaultDetailOpenerTest.kt
- domain/lemmy/pagination/src/androidUnitTest/kotlin/com/diegoberaldin/raccoonforlemmy/domain/lemmy/pagination/DefaultPostPaginationManagerTest.kt
- domain/lemmy/pagination/src/commonMain/kotlin/com/diegoberaldin/raccoonforlemmy/domain/lemmy/pagination/DefaultPostPaginationManager.kt
Add some missing test for `DefaultPostPaginationManager` and fixes a bug concerning liked posts pagination.
> chore: add pagination tests

- core/commonui/lemmyui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/lemmyui/PostCardVideo.kt
There was a bug due to which the loader shown before video playback was not taking the whole space, leaving the player behind it partially visible.
This PR fixes this visual (terrible) effect.
> fix: correct loader above videos

- unit/mentions/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/mentions/InboxMentionsScreen.kt
- unit/mentions/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/mentions/InboxMentionsViewModel.kt
- unit/messages/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/messages/InboxMessagesScreen.kt
- unit/messages/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/messages/components/ChatCard.kt
- unit/messages/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/messages/components/ChatCardPlaceholder.kt
- unit/replies/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/replies/InboxRepliesScreen.kt
- unit/replies/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/replies/InboxRepliesViewModel.kt
It is useless to have to use different actions to mark replies and mentions as read after you have voted, downvoted or even opened the corresponding thread. It will now be possible to mark them as read while voting altogether.
Moreover, since there is a swipe action for it, it is no longer needed to have an options menu in mention/reply cards.
Finally, this PR also improves the messages layout by reducing the amount of wasted space to display the user name and the date on two separate lines.
> enhancement: inbox read replies and mentions

- domain/lemmy/pagination/src/androidUnitTest/kotlin/com/diegoberaldin/raccoonforlemmy/domain/lemmy/pagination/DefaultMultiCommunityPaginatorTest.kt
- domain/lemmy/pagination/src/androidUnitTest/kotlin/com/diegoberaldin/raccoonforlemmy/domain/lemmy/pagination/DefaultPostNavigationManagerTest.kt
This PR adds the last tests that were missing for the `:domain:lemmy:pagination` module.
> chore: add more pagination tests

- domain/lemmy/repository/src/androidUnitTest/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/repository/DefaultGetSortTypesUseCaseTest.kt
- domain/lemmy/repository/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/repository/DefaultGetSortTypesUseCase.kt
This PR adds the tests for `DefaultGetSortTypesUseCase`. Moreover, since the implementation of this use case was very naïve and compared strings instead of version numbers, the class has been updated to make more robust comparisons.
> chore: test for sort types use case

- core/commonui/detailopener-impl/src/androidUnitTest/kotlin/DefaultDetailOpenerTest.kt
- core/navigation/src/androidUnitTest/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/navigation/DefaultNavigationCoordinatorTest.kt
- domain/lemmy/pagination/build.gradle.kts
- domain/lemmy/pagination/src/androidUnitTest/kotlin/com/diegoberaldin/raccoonforlemmy/domain/lemmy/pagination/DefaultCommentPaginationManagerTest.kt
- domain/lemmy/pagination/src/androidUnitTest/kotlin/com/diegoberaldin/raccoonforlemmy/domain/lemmy/pagination/DefaultPostPaginationManagerTest.kt
- domain/lemmy/pagination/src/commonMain/kotlin/com/diegoberaldin/raccoonforlemmy/domain/lemmy/pagination/DefaultCommentPaginationManager.kt
- domain/lemmy/pagination/src/commonMain/kotlin/com/diegoberaldin/raccoonforlemmy/domain/lemmy/pagination/DefaultPostPaginationManager.kt
- domain/lemmy/pagination/src/commonMain/kotlin/com/diegoberaldin/raccoonforlemmy/domain/lemmy/pagination/di/LemmyPaginationModule.kt
With post and comment pagination introduced in, a cache is created for posts and comments that are fetched while scrolling. If a post/comment gets modified due to user interaction (e.g. voting) the change was not reflected in this cache, which might lead to item state being "lost" when the content is fetched again from this cache, e.g. after navigating back to a post list or post detail screen.
This PR fixes this issue and ensures the cache is updated.
> fix: post and comment pagination cache

- unit/drafts/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/drafts/DraftsScreen.kt
- unit/drafts/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/drafts/components/DraftCard.kt
- unit/filteredcontents/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/filteredcontents/FilteredContentsScreen.kt
- unit/reportlist/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/reportlist/ReportListScreen.kt
This PR aims to fix a couple of layout issues with spacing in filtered contents (votes, moderated contents and saved items) and drafts screens.
> fix: duplicate inter-item spacing

- iosApp/iosApp.xcodeproj/project.pbxproj
- iosApp/iosApp/ContentView.swift
This PR contains another couple of fixes for the iOS version of the app, e.g. insets for the safe area applied multiple times (due to Compose-SwiftUI interop).
Moreover, there was an error in the project.pbxproj which prevented the project from building in Xcode.
> fix: improve appearance on iOS

- core/api/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/api/service/PostService.kt
- domain/lemmy/repository/src/androidUnitTest/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/repository/DefaultPostRepositoryTest.kt
- domain/lemmy/repository/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/repository/DefaultPostRepository.kt
- domain/lemmy/repository/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/repository/PostRepository.kt
This PR adds some tests for `DefaultPostRepository` and adds a method to feature post in the instance which will be used for the corresponding admin action in a future PR.
> chore: add test for DefaultPostRepository

- domain/lemmy/repository/src/androidUnitTest/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/repository/DefaultCommunityRepositoryTest.kt
- domain/lemmy/repository/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/repository/CommunityRepository.kt
- domain/lemmy/repository/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/repository/DefaultCommunityRepository.kt
- unit/drawer/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/drawer/ModalDrawerContent.kt
- unit/drawer/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/drawer/ModalDrawerMviModel.kt
- unit/drawer/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/drawer/ModalDrawerViewModel.kt
- unit/managesubscriptions/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/managesubscriptions/ManageSubscriptionsMviModel.kt
- unit/managesubscriptions/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/managesubscriptions/ManageSubscriptionsScreen.kt
- unit/managesubscriptions/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/managesubscriptions/ManageSubscriptionsViewModel.kt
- unit/multicommunity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/multicommunity/editor/MultiCommunityEditorMviModel.kt
- unit/multicommunity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/multicommunity/editor/MultiCommunityEditorScreen.kt
- unit/multicommunity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/multicommunity/editor/MultiCommunityEditorViewModel.kt
- unit/selectcommunity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/selectcommunity/SelectCommunityDialog.kt
- unit/selectcommunity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/selectcommunity/SelectCommunityMviModel.kt
- unit/selectcommunity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/selectcommunity/SelectCommunityViewModel.kt
As observed [on Lemmy](https://lemmy.world/comment/10249351) when a user is subscribed to a lot of communities the side menu, as well as the manage subscription list or the post creation screen, won't load because the results are taken from the GET `/site` call which does not allow pagination for the contents of `myUser.follows`.
The idea to solve this issue is to load the subscription list one page at a time, as normally done for post, comments and search results. This will also improve the search because, until now, filtering on subscriptions was done client-side (sadly, but again because the `/site` endpoint was not intended to be used like that at all).
Moreover, the multi-community editor had been jotted down quite in a rush in October 2023, I found a lot of quite ugly logic I should …
> fix: pagination in subscription list

- core/commonui/detailopener-impl/src/androidUnitTest/kotlin/DefaultDetailOpenerTest.kt
- core/commonui/detailopener-impl/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/detailopener/impl/DefaultDetailOpener.kt
- core/commonui/lemmyui/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/commonui/lemmyui/FabNestedScrollConnection.kt
- core/navigation/src/androidUnitTest/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/navigation/DefaultNavigationCoordinatorTest.kt
- core/navigation/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/navigation/DefaultNavigationCoordinator.kt
- core/notifications/src/androidUnitTest/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/notifications/DefaultNotificationCenterTest.kt
- core/notifications/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/notifications/DefaultNotificationCenter.kt
- core/notifications/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/notifications/di/NotificationModule.kt
- core/testutils/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/testutils/DispatcherTestRule.kt
- core/utils/src/androidUnitTest/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/utils/zombiemode/DefaultZombieModeHelperTest.kt
- core/utils/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/utils/zombiemode/DefaultZombieModeHelper.kt
- domain/identity/src/androidUnitTest/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/identity/repository/DefaultApiConfigurationRepositoryTest.kt
- domain/identity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/identity/repository/DefaultApiConfigurationRepository.kt
- domain/inbox/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/inbox/notification/CheckNotificationWorker.kt
- domain/inbox/src/androidUnitTest/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/inbox/DefaultInboxCoordinatorTest.kt
- domain/inbox/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/inbox/DefaultInboxCoordinator.kt
- domain/lemmy/pagination/src/androidUnitTest/kotlin/com/diegoberaldin/raccoonforlemmy/domain/lemmy/pagination/DefaultCommentPaginationManagerTest.kt
- domain/lemmy/pagination/src/androidUnitTest/kotlin/com/diegoberaldin/raccoonforlemmy/domain/lemmy/pagination/DefaultPostPaginationManagerTest.kt
- domain/lemmy/pagination/src/commonMain/kotlin/com/diegoberaldin/raccoonforlemmy/domain/lemmy/pagination/DefaultCommentPaginationManager.kt
- domain/lemmy/pagination/src/commonMain/kotlin/com/diegoberaldin/raccoonforlemmy/domain/lemmy/pagination/DefaultPostPaginationManager.kt
This PR makes the coroutine dispatcher injectable in order to override it in tests and prevent flakiness.
> fix: flaky tests due to concurrency issues

- .github/workflows/android.yml
- CONTRIBUTING.md
- README.md
- androidApp/src/main/java/com/github/diegoberaldin/raccoonforlemmy/android/MainActivity.kt
- docs/tech_manual/setup.md
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
This PR updates Gradle to 8.8 and bumps some dependencies (androidx.activity, androidx.core, androidx.media3 and kotlinx.coroutines).
> chore: update Gradle to version 8.8

- unit/chat/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/chat/InboxChatScreen.kt
- unit/createpost/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/createpost/CreatePostScreen.kt
- unit/multicommunity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/multicommunity/editor/MultiCommunityEditorScreen.kt
The type in `KeyboardOptions` was incorrectly set to `KeyboardType.Ascii` instead of `KeyboardType.Text` for some fields which should in turn accept regular text inputs.
> fix: keyboard type for text inputs

- core/markdown/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/Utils.kt
There was an issue in the Markdown renderer for when an empty link(`[]()`)  is found in the input. This PR adds a sanitization step to replace offending characters.
> fix: sanitize markdown for empty links

- feature/settings/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/feature/settings/advanced/AdvancedSettingsViewModel.kt
This PR fixes a bug in the initial loading of the advanced settings screen, due to which the value of the inbox background check period is not populated with the current value.
> fix: populate inbox check period in advanced settings

- core/api/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/api/dto/LocalUserView.kt
- core/api/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/api/dto/LocalUserVoteDisplayMode.kt
- core/api/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/api/dto/SaveUserSettingsForm.kt
- domain/identity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/identity/usecase/DefaultLoginUseCase.kt
- domain/lemmy/data/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/data/AccountSettingsModel.kt
- domain/lemmy/repository/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/repository/DefaultSiteRepository.kt
- domain/lemmy/repository/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/lemmy/repository/utils/Mappings.kt
- unit/accountsettings/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/accountsettings/AccountSettingsMviModel.kt
- unit/accountsettings/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/accountsettings/AccountSettingsScreen.kt
- unit/accountsettings/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/accountsettings/AccountSettingsViewModel.kt
This PR enables the app to read and write the properties of the `local_user_vote_display_mode` object embedded in `LocalUserView` for vote display mode.
Epic reference: #946
> feat: manage local user vote display mode

- core/markdown/build.gradle.kts
- core/markdown/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/ProvideImageTransformer.kt
- core/markdown/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/CustomMarkdownWrapper.kt
- core/markdown/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/ProvideImageTransformer.kt
- core/markdown/src/iosMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/ProvideImageTransformer.kt
- gradle/libs.versions.toml
This PR manually updates MikePenz's multiplatform markdown renderer to version 0.21.0 because it requires manual resolution and the dependabot would have created an invalid PR.
> chore: bump multiplatform-markdown-renderer from 0.20.0-coil2 to 0.21.0

- scripts/convert_kt_to_xml.py
This PR introduces a Python script that converts Kotlin source files to Android XML resources (e.g. for compatibilities with L10n platforms such as Weblate).
> chore: add script to generate XMLs from l10n sources

- unit/postdetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/postdetail/PostDetailScreen.kt
- unit/postdetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/postdetail/PostDetailViewModel.kt
This PR fixes a series of bugs related to comment navigation:
- the initial index was not calculated correctly because it didn't account for the initial item (the post card) which caused indices to be off-by-one
- the navigation to next comment skipped all the comments visible in the current screen and started from the bottom one, resulting in big "leaps" when navigating to the next one.
> fix: comment navigation

- unit/postdetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/postdetail/PostDetailViewModel.kt
This PR solves a bug which occurred at the beginning and at the end of the list, avoiding back and forth jumps.
> fix: comment navigation at list ends

- core/persistence/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/persistence/data/ActionOnSwipe.kt
- unit/communitydetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/communitydetail/CommunityDetailScreen.kt
- unit/configureswipeactions/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/configureswipeactions/ConfigureSwipeActionsScreen.kt
- unit/configureswipeactions/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/configureswipeactions/ConfigureSwipeActionsViewModel.kt
- unit/postdetail/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/postdetail/PostDetailScreen.kt
- unit/postlist/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/postlist/PostListScreen.kt
This PR adds the "Edit" option to the swipe action list for posts and comments. The action should be available only if the author of such items is the current user.
> feat: edit swipe action

- core/markdown/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/Utils.kt
This PR replaces `U+0024` characters with `U+FF04` (full-width dollar sign) to avoid a bug in how annotated strings are built inside the Markdown rendering library.
> fix: workaround for dollar sign in Markdown

- core/markdown/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/Regexes.kt
- core/markdown/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/Utils.kt
There is another weird bug in the renderer due to which images after a newline are neither inline nor treated as a block on their own, and instead overlap each other (and have the wrong height).
This PR introduces a quick workaround for that.
> fix: workaround for images after a newline

- core/markdown/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/markdown/Utils.kt
This PR replaces some common elements of Markdown syntax which are escaped in the source text with equivalent characters to avoid rendering the backslash (which is not recognized as an escape character by the library) and messing up the subsequent syntax.
> fix: workaround for markdown escapes

- core/api/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/api/dto/LoginResponse.kt
- domain/identity/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/domain/identity/usecase/DefaultLoginUseCase.kt
The PR allows `LoginResponse` properties to be null and adds the `error` property to receive error messages from the API. 
Adds a check to see if `error` is not null and throws an exception with a user friendly message.
Addresses #1005
> Process error messages from instances.

- core/utils/src/androidMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/utils/network/DefaultNetworkManager.kt
Not 100% sure about this one - would definitely appreciate feedback! 
This PR removes deprecated methods and simplifies the existing, as the methods used are available SDK version 23, and the minimum for the project is 26. 
`isNetworkAvailable` should return `true` if a connection is active and has internet access, otherwise returns `false`.
> Simplify network availability checks

- core/persistence/src/androidUnitTest/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/persistence/repository/DefaultAccountRepositoryTest.kt
- core/persistence/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/persistence/repository/DefaultAccountRepository.kt
- core/persistence/src/commonMain/sqldelight/com/github/diegoberaldin/raccoonforlemmy/core/persistence/accounts.sq
This PR fixes a bug which led to account duplication if, while switching account and selecting "Add new account" you entered the same credentials but with a different capitalization on the username/instance fields.
> fix: case sensitive account lookup

- core/navigation/src/androidUnitTest/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/navigation/DefaultNavigationCoordinatorTest.kt
- core/navigation/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/navigation/DefaultNavigationCoordinator.kt
- core/navigation/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/core/navigation/NavigationCoordinator.kt
- unit/drawer/src/commonMain/kotlin/com/github/diegoberaldin/raccoonforlemmy/unit/drawer/ModalDrawerContent.kt
This PR fixes a bug due to which selecting All/Subscribed/Local from the navigation drawer when in a subsection (e.g. community detail or user detail) did not do anything.
> fix: shortcut selection for feeds from navigation drawer
